### ISSUE TITLE
초보자모드로 배포 후 서버가 금방 꺼지는 문제가 있습니다.

### ISSUE THREAD

**Issue by Seungyeoljeon** [woensug-choi/ChatGee#3]
너무 잘 이용했습니다.
1. 대화 입력 후
"죄송해요 🙇🙇🙇
생각이 길어지고 있어요 🤔💭
잠시후 아래 말풍선을 눌러주세요"
라는 문장이 자주 나옵니다.
원인은 
서버가 꺼진경우,
답변 받아오는게 늦어진 경우,로 추정됩니다.

서버를 오래 유지하는 방법,
답변 받아오는 시간을 길게 만드려면 
settings.yami 에서RESPONSE_SAFE_TIME: 3.4를 조정하면 될까요?
RESPONSE_SAFE_TIME: 3.4

**Comment by woensug-choi** [comment]
디버깅의 길에 들어오신걸 환영합니다..!

나오는 문구는 RESPONSE_SAFE_TIME을 넘어서 답변할떄 나오는건데, 말이 길어지면 대부분 넘어가서 거의 항상 나오는게 맞습니다. 서버가 꺼진게 아니라면 `/local_test`에서는 `'생각 다 했니???!`(문자 그대로, 물음표갯수도 그대로) 입력하면 저장된 응답을 줄겁니다. 챗봇이라면 챗지와 같이 버튼으로 주어질 거구요. RESPONSE_SAFE_TIME를 수정하는건 권장하지 않습니다.

**Comment by woensug-choi** [comment]
곧 더 안정적인 구동방법 업데이트가 있을 예정입니다!

**Comment by woensug-choi** [comment]
Ngrok를 사용하는 버전으로 사용설명서와 소스코드 모두 업데이트 되었습니다! 사용해보시기 바랍니다!
